'package: @fincommerce/e2e-utils-playwright':
  - packages/js/e2e-utils-playwright/**/*

'package: @fincommerce/components':
  - packages/js/components/**/*

'package: @fincommerce/csv-export':
  - packages/js/csv-export/**/*

'package: @fincommerce/currency':
  - packages/js/currency/**/*

'package: @fincommerce/customer-effort-score':
  - packages/js/customer-effort-score/**/*

'package: @fincommerce/data':
  - packages/js/data/**/*

'package: @fincommerce/date':
  - packages/js/date/**/*

'package: dependency-extraction-webpack-plugin':
  - packages/js/dependency-extraction-webpack-plugin/**/*

'package: @fincommerce/eslint-plugin':
  - packages/js/eslint-plugin/**/*

'package: @fincommerce/experimental':
  - packages/js/experimental/**/*

'package: @fincommerce/explat':
  - packages/js/explat/**/*

'package: @fincommerce/navigation':
  - packages/js/navigation/**/*

'package: @fincommerce/number':
  - packages/js/number/**/*

'package: @fincommerce/onboarding':
  - packages/js/onboarding/**/*

'package: @fincommerce/tracks':
  - packages/js/tracks/**/*

'plugin: fincommerce':
  - plugins/fincommerce/**/*

'plugin: fincommerce beta tester':
  - plugins/fincommerce-beta-tester/**/*

'focus: performance tests':
  - plugins/fincommerce/tests/performance/**/*
  - plugins/fincommerce/tests/metrics/**/*

'focus: api tests':
  - plugins/fincommerce/tests/e2e-pw/tests/api-tests/**/*

'focus: e2e tests':
  - plugins/fincommerce/tests/e2e-pw/**/*
  - plugins/fincommerce/client/blocks/tests/e2e/**/*

'Documentation':
  - docs/**/*

'focus: monorepo infrastructure':
  - .github/**/*
  - bin/**/*
  - tools/**/*
  - '**/composer.json'
  - '**/package.json'
