name: fincommerce Beta Tester Release
permissions: {}

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version number for the release'
                required: true

jobs:
    release:
        name: Run release scripts
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Setup fincommerce Monorepo
              uses: ./.github/actions/setup-fincommerce-monorepo
              with:
                install: '@fincommerce/plugin-fincommerce-beta-tester...'
                build: '@fincommerce/plugin-fincommerce-beta-tester...'
                pull-package-deps: '@fincommerce/plugin-fincommerce-beta-tester'

            - name: Build fincommerce Beta Tester Zip
              working-directory: plugins/fincommerce-beta-tester
              run: pnpm build:zip

            - name: Create release
              id: create_release
              uses: fincommerce/action-gh-release@master
              with:
                  tag_name: wc-beta-tester-${{ inputs.version }}
                  name: fincommerce Beta Tester Release ${{ inputs.version }}
                  draft: false
                  files: plugins/fincommerce-beta-tester/fincommerce-beta-tester.zip
