name: Storybook GitHub Pages

on:
    schedule:
        - cron: '30 2 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'fincommerce/fincommerce' }}

        steps:
            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
              with:
                  ref: trunk
                  fetch-depth: 0

            - name: Setup fincommerce Monorepo
              uses: ./.github/actions/setup-fincommerce-monorepo
              with:
                  install: true

            - name: Build Storybook
              run: pnpm --filter='@fincommerce/storybook' build
              env:
                  STORYBOOK_COMPOSITION_PATH_PREFIX: /fincommerce

            - name: Deploy
              uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./tools/storybook/storybook-static
                  force_orphan: true
