name: Test canonical extensions

on:
  workflow_dispatch:
    inputs:
      woocommerce_version:
        description: 'WooCommerce version to use for testing (as per https://qit.woo.com/wp-json/cd/v1/environment)'
        required: true
      wordpress_version:
        description: 'WordPress version to use for testing (as per https://qit.woo.com/wp-json/cd/v1/environment)'
        required: false
        default: ''
      php_version:
        description: 'PHP version to use for testing (as per https://qit.woo.com/wp-json/cd/v1/environment)'
        required: false
        default: ''

jobs:
  run-tests:
    name: Test canonical extensions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Run target repositories testing workflows
        env:
            GH_TOKEN: ${{ secrets.PR_ASSIGN_TOKEN }}
            GH_REPO: ${{ github.repository }}
        run: |
            printf "${{ github.event.inputs.woocommerce_version }}\n${{ github.event.inputs.wordpress_version }}\n${{ github.event.inputs.php_version }}\n\n" | pnpm run-canonical-extensions-tests
