name: 'Update contributor feedback labels on comment'
on: 'issue_comment'

permissions: {}

jobs:
  feedback:
    if: |
      github.actor != 'github-actions' &&
      github.actor == github.event.issue.user.login &&
      github.event.issue &&
      github.event.issue.state == 'open' &&
      contains(github.event.issue.labels.*.name, 'needs: author feedback')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Add has feedback
      uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf #v1.1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'needs: triage feedback'
    - name: remove needs feedback
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'needs: author feedback'
    - name: remove stale
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'status: stale'
